"""recreate knowledge chunk table

Revision ID: 083a55876f2d
Revises: ea77409fe79f
Create Date: 2026-07-29 17:51:15.786133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '083a55876f2d'
down_revision: Union[str, Sequence[str], None] = 'ea77409fe79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=3072),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_chunks', 'embedding',
               existing_type=Vector(dim=3072),
               type_=Vector(dim=768),
               existing_nullable=False)
    # ### end Alembic commands ###
