"""add message type

Revision ID: 1b2ca423e237
Revises: c068678ed939
Create Date: 2026-07-29 15:23:51.706814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '1b2ca423e237'
down_revision: Union[str, Sequence[str], None] = 'c068678ed939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    message_type_enum = postgresql.ENUM('TEXT', 'IMAGE', name='messagetype')
    message_type_enum.create(op.get_bind())
    op.add_column('messages', sa.Column('message_type', sa.Enum('TEXT', 'PET_CARD', name='messagetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'message_type')
    
    # 2. Xóa Type ENUM sau
    message_type_enum = postgresql.ENUM('TEXT', 'IMAGE', name='messagetype')
    message_type_enum.drop(op.get_bind())
    # ### end Alembic commands ###
