"""drop table

Revision ID: 47a31925122c
Revises: 1b2ca423e237
Create Date: 2026-07-29 16:31:51.523818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a31925122c'
down_revision: Union[str, Sequence[str], None] = '1b2ca423e237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_embeddings_message_id'), table_name='message_embeddings')
    op.drop_table('message_embeddings')
    op.drop_table('pet_embeddings')
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', name='messagetype'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'message_type',
               existing_type=postgresql.ENUM('TEXT', 'IMAGE', name='messagetype'),
               nullable=True)
    op.create_table('pet_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('pet_embeddings_pet_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pet_embeddings_pkey')),
    sa.UniqueConstraint('pet_id', name=op.f('pet_embeddings_pet_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('message_embeddings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_embeddings_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_embeddings_pkey'))
    )
    op.create_index(op.f('ix_message_embeddings_message_id'), 'message_embeddings', ['message_id'], unique=True)
    # ### end Alembic commands ###
